project:
  type: website

website:
  title: "Flat Moon Society (AUS)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/calvpang/FMS_Moonquake
format:
  html:
    theme: flatly
    css: styles.css



