project:
  type: website

website:
  title: "NASA Moonquake Challenge 2022"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/calvpang/FMS_Moonquake
format:
  html:
    theme: darkly
    css: styles.css



